name: SpellCheck

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install CSpell
        run: npm install -g cspell

      - name: Run CSpell
        run: cspell --config .spell-check/.cspell.json "**/*"
